export type WordCategory =
  | "aleatorio"
  | "comida"
  | "películas"
  | "lugares"
  | "objetos"
  | "acotar_saga"
  | "lam_panelistas"
  | "politicos_argentinos"
  | "conductores_streaming_argentinos"
  | "farandula_argentina"
  | "cantantes_argentinos"
  | "rock_nacional"
  | "provincias_argentinas"
  | "barrios_porteños"
  | "jugadores_argentinos_futbol"
  | "equipos_futbol_argentinos"
  | "personalizado"
  | "ia_generado";

export interface Player {
  id: number;
  name: string;
  isImpostor: boolean;
}

export interface GameState {
  players: Player[];
  numberOfPlayers: number;
  numberOfImpostors: number;
  secretWord: string;
  category: WordCategory;
  phase: "setup" | "roles" | "complete";
  currentPlayerIndex: number;
}

export const WORD_LISTS: Record<Exclude<WordCategory, "aleatorio" | "personalizado" | "ia_generado">, string[]> = {
  comida: [
    "Pizza", "Sushi", "Tacos", "Hamburguesa", "Paella", "Pasta",
    "Helado", "Chocolate", "Café", "Té", "Queso", "Pan",
    "Arroz", "Empanada", "Ensalada", "Milanesa", "Arepa",
    "Tortilla", "Fideos", "Pollo", "Carne", "Pescado",
    "Sopa", "Gazpacho", "Ceviche", "Tamales", "Ramen",
    "Gnocchi", "Lasaña", "Curry", "Falafel", "Hummus",
    "Sandwich", "Churro", "Croqueta", "Galleta", "Tarta",
    "Frutilla", "Manzana", "Banana", "Uva", "Naranja",
    "Mandarina", "Durazno", "Pera", "Mango", "Kiwi"
  ],
  películas: [
    "Titanic", "Avatar", "Matrix", "Gladiador", "Joker", "Inception",
    "Interestelar", "Parasite", "Toy Story", "El Padrino", "Pulp Fiction",
    "Forrest Gump", "El Señor de los Anillos", "Star Wars", "Harry Potter",
    "Jurassic Park", "El Rey León", "La La Land", "Spider-Man", "Batman",
    "Los Vengadores", "Iron Man", "Capitán América", "Black Panther",
    "Frozen", "Shrek", "Coco", "Los Increíbles", "Up",
    "Buscando a Nemo", "Rocky", "Terminator", "Alien", "Indiana Jones",
    "Volver al Futuro", "El Exorcista", "El Club de la Pelea", "Kill Bill",
    "La Lista de Schindler", "El Pianista", "Mad Max", "Whiplash", "Dune",
    "Oppenheimer", "Barbie", "La Forma del Agua", "Amélie", "Gravity"
  ],
  lugares: [
    "París", "Playa", "Montaña", "Museo", "Hospital", "Escuela",
    "Aeropuerto", "Restaurante", "Gimnasio", "Biblioteca", "Parque",
    "Cine", "Teatro", "Supermercado", "Estadio", "Hotel",
    "Iglesia", "Terminal", "Puerto", "Mercado", "Fábrica",
    "Oficina", "Banco", "Plaza", "Zoológico", "Acuario",
    "Campo", "Desierto", "Selva", "Bosque", "Isla",
    "Cafetería", "Bar", "Discoteca", "Farmacia", "Jardín",
    "Pueblo", "Ciudad", "Castillo", "Puente", "Túnel",
    "Estación", "Río", "Lago", "Volcán", "Cascada"
  ],
  objetos: [
    "Teléfono", "Reloj", "Computadora", "Llave", "Silla", "Mesa",
    "Libro", "Lámpara", "Guitarra", "Pelota", "Cámara", "Bolígrafo",
    "Cuaderno", "Mochila", "Botella", "Vaso", "Cepillo",
    "Peine", "Carpeta", "Cuchillo", "Tenedor", "Cuchara",
    "Televisor", "Control", "Toalla", "Almohada", "Colchón",
    "Ventilador", "Auriculares", "Cargador", "Billetera", "Moneda",
    "Llavero", "Martillo", "Destornillador", "Linterna", "Rueda",
    "Ropa", "Zapato", "Calcetín", "Caja", "Reloj despertador",
    "Tablero", "Pincel", "Tijera", "Regla", "Imán"
  ],
  acotar_saga: [
    "Feyre", "Rhysand", "Tamlin", "Lucien", "Mor", "Azriel", "Cassian",
    "Amren", "Nesta", "Elain", "Suriel", "Jurian", "Hybern", "Ianthe",
    "Tarquin", "Helion", "Beron", "Merrion", "Miryam", "Drakon",
    "Prythian", "Velaris", "Corte Noche", "Corte Primavera",
    "Corte Verano", "Corte Otoño", "Corte Invierno", "Corte Día",
    "Illyria", "Sidra"
  ],
  lam_panelistas: [
    "Ángel de Brito",
    "Yanina Latorre",
    "Andrea Taboada",
    "Karina Iavícoli",
    "Mariana Brey",
    "Pía Shaw",
    "Nazarena Vélez",
    "Maite Peñoñori",
    "Cinthia Fernández",
    "Estefi Berardi",
    "Lourdes Sánchez",
    "Nequi Galotti",
    "Graciela Alfano",
    "Marixa Balli",
    "Fernanda Iglesias",
    "Ana Rosenfeld",
    "Marcela Feudale",
    "Sofía Jiménez",
    "Mónica Farro",
    "Gladys Tucumana",
    "Micaela Viciconte",
    "Andrea Rincón",
    "Fanny Mandelbaum"
  ],
  politicos_argentinos: [
    "Javier Milei",
    "Cristina Fernández de Kirchner",
    "Mauricio Macri",
    "Alberto Fernández",
    "Sergio Massa",
    "Patricia Bullrich",
    "Horacio Rodríguez Larreta",
    "Axel Kicillof",
    "Néstor Kirchner",
    "Elisa Carrió",
    "Daniel Scioli",
    "Martín Lousteau",
    "Myriam Bregman",
    "José Luis Espert",
    "Juan Grabois",
    "Ricardo López Murphy",
    "Wado de Pedro",
    "María Eugenia Vidal",
    "Aníbal Fernández",
    "Florencio Randazzo",
    "Miguel Ángel Pichetto"
  ],
  conductores_streaming_argentinos: [
    "Migue Granados",
    "Nico Occhiato",
    "Luquitas Rodríguez",
    "Nati Jota",
    "Diego Leuco",
    "Damián Betular",
    "Mario Pergolini",
    "Flor Jazmín Peña",
    "Nacho Elizalde",
    "Momi Giardina",
    "Germán Beder",
    "Alfredo Montes de Oca",
    "Roberto (3 bombas) Galati",
    "Paula Chaves",
    "Tomás Rebord",
    "Pedro Rosemblat",
    "Ángela Torres",
    "Marcos Giles",
    "Joaquín Cavanna"
  ],
  farandula_argentina: [
    "Wanda Nara",
    "Mauro Icardi",
    "Pampita Ardohain",
    "China Suárez",
    "Marcelo Tinelli",
    "Moria Casán",
    "Susana Giménez",
    "Mirtha Legrand",
    "Florencia de la V",
    "Yanina Latorre",
    "Zaira Nara",
    "Jorge Rial",
    "Intrusos",
    "Marcelo Polino",
    "Carmen Barbieri",
    "Fede Bal",
    "Laurita Fernández",
    "Nicole Neumann",
    "Mica Viciconte",
    "Tini Stoessel",
    "Rodrigo de Paul",
    "Luciana Salazar",
    "Charlotte Caniggia",
    "Alexander Caniggia",
    "Barby Franco",
    "Fernando Burlando",
    "Cinthia Fernández",
    "Marcelo Polino",
    "Sofía Zámolo",
    "Flor Peña",
    "Guido Kaczka",
    "Jimena Barón",
    "Agustina Casanova",
    "Verónica Lozano",
    "Jey Mammón",
    "Marley",
    "Stefi Roitman",
    "Benjamín Vicuña",
    "Horacio Cabak",
    "Viviana Canosa"
  ],
  cantantes_argentinos: [
    "Charly García",
    "Fito Páez",
    "Luis Alberto Spinetta",
    "Andrés Calamaro",
    "Gustavo Cerati",
    "Mercedes Sosa",
    "León Gieco",
    "Abel Pintos",
    "Soledad Pastorutti",
    "Luciano Pereyra",
    "Lali Espósito",
    "Tini Stoessel",
    "Duki",
    "Bizarrap",
    "Maria Becerra",
    "Wos",
    "Paulo Londra",
    "Trueno",
    "Nicki Nicole",
    "Emilia Mernes",
    "Patricio Rey",
    "La Renga",
    "Fabiana Cantilo",
    "Valeria Lynch",
    "Axel",
    "Ciro Martínez",
    "Babasonicos",
    "Miranda",
    "Vicentico",
    "Pablo Lescano",
    "Rodrigo",
    "Él Mató a un Policía Motorizado",
    "Diego Torres",
    "Pedro Aznar",
    "Marcela Morelo",
    "Kevin Johansen",
    "Chano"
  ],
  rock_nacional: [
    "Soda Stereo",
    "Gustavo Cerati",
    "Charly García",
    "Luis Alberto Spinetta",
    "Pappo",
    "Fito Páez",
    "Andrés Calamaro",
    "Los Fabulosos Cadillacs",
    "Patricio Rey y sus Redonditos de Ricota",
    "La Renga",
    "Divididos",
    "Sumo",
    "Bersuit Vergarabat",
    "Virus",
    "Los Enanitos Verdes",
    "Los Tipitos",
    "Las Pelotas",
    "Ciro y los Persas",
    "Riff",
    "Almendra",
    "Pescado Rabioso",
    "Sui Generis",
    "Invisible",
    "Spinetta Jade",
    "Babasónicos",
    "Ratones Paranoicos",
    "Estelares",
    "La Mississippi",
    "Kapanga",
    "Los Auténticos Decadentes",
    "El Bordo",
    "Eruca Sativa",
    "Airbag",
    "O'Connor",
    "Carajo",
    "Los Caballeros de la Quema",
    "Viejas Locas",
    "Intoxicados",
    "Guasones",
    "Don Osvaldo"
  ],
  provincias_argentinas: [
    "Buenos Aires",
    "CABA",
    "Catamarca",
    "Chaco",
    "Chubut",
    "Córdoba",
    "Corrientes",
    "Entre Ríos",
    "Formosa",
    "Jujuy",
    "La Pampa",
    "La Rioja",
    "Mendoza",
    "Misiones",
    "Neuquén",
    "Río Negro",
    "Salta",
    "San Juan",
    "San Luis",
    "Santa Cruz",
    "Santa Fe",
    "Santiago del Estero",
    "Tierra del Fuego",
    "Tucumán"
  ],
  barrios_porteños: [
    "Palermo",
    "Recoleta",
    "Belgrano",
    "Retiro",
    "San Telmo",
    "La Boca",
    "Puerto Madero",
    "Almagro",
    "Caballito",
    "Flores",
    "Floresta",
    "Villa Urquiza",
    "Villa Crespo",
    "Chacarita",
    "Colegiales",
    "Núñez",
    "Saavedra",
    "Villa Devoto",
    "Villa del Parque",
    "Villa Pueyrredón",
    "Parque Patricios",
    "Constitución",
    "Balvanera",
    "Monserrat",
    "San Nicolás",
    "Barracas",
    "Mataderos",
    "Liniers",
    "Villa Luro",
    "Versalles",
    "Monte Castro",
    "Parque Chacabuco",
    "Boedo",
    "Parque Avellaneda",
    "Villa Lugano",
    "Villa Soldati",
    "Nueva Pompeya",
    "San Cristóbal",
    "Agronomía",
    "Paternal",
    "Villa Ortúzar"
  ],
  jugadores_argentinos_futbol: [
    "Lionel Messi",
    "Diego Maradona",
    "Ángel Di María",
    "Sergio Agüero",
    "Gonzalo Higuaín",
    "Paulo Dybala",
    "Lautaro Martínez",
    "Enzo Fernández",
    "Emiliano Martínez",
    "Rodrigo De Paul",
    "Leandro Paredes",
    "Julián Álvarez",
    "Nicolás Otamendi",
    "Juan Román Riquelme",
    "Carlos Tevez",
    "Javier Mascherano",
    "Pablo Aimar",
    "Fernando Redondo",
    "Gabriel Batistuta",
    "Hernán Crespo",
    "Claudio Caniggia",
    "Ariel Ortega",
    "Roberto Ayala",
    "Walter Samuel",
    "Oscar Ruggeri",
    "Emiliano Buendía",
    "Giovani Lo Celso",
    "Marcos Acuña",
    "Germán Pezzella",
    "Nahuel Molina"
  ],
  equipos_futbol_argentinos: [
    "Boca Juniors",
    "River Plate",
    "Independiente",
    "Racing Club",
    "San Lorenzo",
    "Vélez Sarsfield",
    "Huracán",
    "Estudiantes de La Plata",
    "Gimnasia de La Plata",
    "Lanús",
    "Banfield",
    "Argentinos Juniors",
    "Newell's Old Boys",
    "Rosario Central",
    "Colón",
    "Unión",
    "Talleres",
    "Belgrano",
    "Godoy Cruz",
    "Atlético Tucumán",
    "Central Córdoba",
    "Sarmiento",
    "Tigre",
    "Arsenal",
    "Platense",
    "Barracas Central",
    "Instituto",
    "Defensa y Justicia",
    "Aldosivi",
    "Patronato",
    "Nueva Chicago"
  ]
};
